# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a116665b83dfa1bf89ff2fa788b77848"
name = "order-cancel-app"
handle = "order-cancel-app"
application_url = "https://morning-wax-indie-ontario.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-82eb1b1f.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://morning-wax-indie-ontario.trycloudflare.com/auth/callback",
  "https://morning-wax-indie-ontario.trycloudflare.com/auth/shopify/callback",
  "https://morning-wax-indie-ontario.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[pos]
embedded = false
