# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "14046289f23913234d84ce5b5e2b2d33"
name = "Order Editor"
handle = "order-editor-3"
application_url = "https://chapel-warcraft-nelson-gb.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-82eb1b1f.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_assigned_fulfillment_orders,read_customers,read_orders,write_assigned_fulfillment_orders,write_order_edits,write_orders,write_products"

[auth]
redirect_urls = [
  "https://chapel-warcraft-nelson-gb.trycloudflare.com/auth/callback",
  "https://chapel-warcraft-nelson-gb.trycloudflare.com/auth/shopify/callback",
  "https://chapel-warcraft-nelson-gb.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[app_proxy]
url = "https://chapel-warcraft-nelson-gb.trycloudflare.com"
subpath = "orders"
prefix = "apps"

[pos]
embedded = true
