# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c044f0dc05f65ac1590d2f5b83251cf6"
name = "order-cancel-app"
handle = "order-cancel-app-2"
application_url = "https://prot-gentle-letter-stevens.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-4e8ca8f9.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_assigned_fulfillment_orders,read_customers,read_orders,write_assigned_fulfillment_orders,write_order_edits,write_orders,write_products"

[auth]
redirect_urls = [
  "https://prot-gentle-letter-stevens.trycloudflare.com/auth/callback",
  "https://prot-gentle-letter-stevens.trycloudflare.com/auth/shopify/callback",
  "https://prot-gentle-letter-stevens.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

[app_proxy]
url = "https://prot-gentle-letter-stevens.trycloudflare.com"
subpath = "orders"
prefix = "apps"

[pos]
embedded = false
